apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gb7qqmb10-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/gb7qqmb10-java-springboot-gitops